title: GMS Ruins Video Games
tagline: Wherein I spend too much time with games
description: >-
  A Scottish nerd pokes at ancient video games until either they or he cries.
baseurl: ""
url: ""

avatar: assets/img/avatar.png

lang: en
timezone: Europe/London

github_username: GenericMadScientist
github:
  username: GenericMadScientist

twitter:
  username: GMS_CH

social:
  name: GenericMadScientist
  email: rayw1710@gmail.com
  links:
    - https://github.com/GenericMadScientist
    - https://twitter.com/GMS_CH

theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed

feed:
  path:
    assets/feed.xml

comments:
  active: false

toc: true

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
