title: GMS Ruins Video Games
tagline: Wherein I spend too much time with games
description: >-
  A Scottish nerd pokes at ancient video games until either they or he cries.
baseurl: ""
url: ""

avatar: assets/img/avatar.png

lang: en-GB
timezone: Europe/London

github_username: GenericMadScientist
github:
  username: GenericMadScientist

social:
  name: GMS
  email: rayw1710@gmail.com
  links:
    - https://github.com/GenericMadScientist

theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed

feed:
  path:
    assets/feed.xml

disqus:
  comments: false
  shortname: ''

paginate: 10
