matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore Python code blocks
      - open: '(?s)^(\{% highlight python %\})$'
        close: '(?s)^(\{% endhighlight %\})$'
      # Ignore links to other posts
      - open: '\{%'
        close: '%\}'
  sources:
  - '**/*.md'
  default_encoding: utf-8
