# Credits to https://www.swild.dev/self-hosting/github-spellcheck-lint-action/
# for a starting point

name: Spellcheck
on:
  push:
    branches:
      - master
      - check-spelling

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.20.0
        with:
          config_path: config/.spellcheck.yml
      - uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: config/.markdownlint.yml
