# Credits to https://www.swild.dev/self-hosting/github-spellcheck-lint-action/
# for a starting point

name: Spellcheck Action
on: push
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.14.0
        with:
          config_path: config/.spellcheck.yml
